# Start from a base Go image
FROM golang:1.17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application source code
COPY ./backend-A .

# Build the Go application
RUN go build -o backend-a .

# Expose the port that the application listens on
EXPOSE 8080

# Set the entry point to run the built Go application
CMD ["./backend-a"]