apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: book-svc
  name: book-svc
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: book-svc
    spec:
      containers:
      - image: ghcr.io/infracloudio/book-svc:latest
        imagePullPolicy: IfNotPresent
        name: book-svc
        ports:
        - containerPort: 8080
        resources: {}
        env:
        - name: BACKEND_ENV
          value: "book-svc"
        - name: VERSION
          value: "primary"
        - name: HEADER
          value: "x-backend"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-svc
  name: book-svc
  namespace: test
spec:
  ports:
  - name: 50051-50051
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: book-svc
  type: ClusterIP