apiVersion: apps/v1
kind: Deployment
metadata:
  name: forwarder-deployment
  namespace: test
  labels:
    app: forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwarder
  template:
    metadata:
      labels:
        app: forwarder
    spec:
      containers:
      - name: forwarder
        image: ghcr.io/infracloudio/forwarder:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "BACKEND_URL"
          value: "http://book-svc:8080"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: forwarder-service
  namespace: test
spec:
  selector:
    app: forwarder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080